version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - urlshortener_net

  app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - mongodb
    networks:
      - urlshortener_net

  test:
    build: .
    depends_on:
      - app
      - mongodb
    command: python test.py
    networks:
      - urlshortener_net

networks:
  urlshortener_net:
